@startuml

class App {
    + main()
    + start()
}

class ToDoController {
+ addList()
+ openList()
+ saveList()
+ makeItem()
+ showAll()
+ showIncomplete()
+ showComplete()
}
'Req 1
class ToDoList {
- Title : String
- Items : ArrayList
- numItems : int

+setTitle()
+getTitle() : String
+getItem() : Item
+addItem()
'Req 4
+removeItem()
'Req 5
+editItem()
'Req 7, Req 8
+clearAllItems()
'Req 6
+markItemComplete()
+markItemIncomplete()
'Req 9
+sortItemAll() : ArrayList
'Req 10
+sortItemIncomplete() : ArrayList
'Req 11
+sortItemComplete() : ArrayList
'Req 12
+sortItemDate()
+exportList()
'Req 13
+loadList()
'Req 14
}

class Item {
- Description : String
'Req 2
- DueDate : Date
'Req 3
'Format: YYYY-MM-DD
- Complete : Boolean

+ getDescription() : String
+ setDescription()
+ getDueDate() : String
+ setDueDate()
+ validateDate() : Boolean
'Req 3.1: see if 1)DD doesn't go past max for the month, 2)positive numbers
+ markComplete()
+ markIncomplete()
}

ToDoList "1 " *-- "many" Item
App - ToDoController
ToDoController -- ToDoList
javafx.Application <|-- App
@enduml